name: Build Sherpa TTS Android APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK (Target arm64-v8a)
        working-directory: android/SherpaOnnxTtsEngine
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug -Ptarget-abi=arm64-v8a --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sherpa-arm64-tts
          path: android/SherpaOnnxTtsEngine/app/build/outputs/apk/debug/*.apk
